export type ProjectStatus = "flagship" | "shipped";

export type Project = {
  id: string;
  name: string;
  tagline: string;
  description: string;
  stack: string[];
  repo?: string;
  live?: string;
  status: ProjectStatus;
};

export const projects: Project[] = [
  {
    id: "vartalapp",
    name: "VartalApp",
    tagline: "Full-stack collaborative classroom platform — I ran it as Project Manager.",
    description:
      "A cross-device collaborative classroom application: screen sharing, video sharing, chat, a collaborative canvas, AI assistance, cloud persistence, and file sharing.",
    stack: ["Java", "Spring Boot", "Swing", "SQLite"],
    status: "flagship",
  },
  {
    id: "splitzy-pay",
    name: "Splitzy Pay",
    tagline: "Full-stack financial management application.",
    description:
      "A financial analytics platform supporting expense forecasting, spending behavior analysis, and budget optimization, with UPI-style transfers, expense groups, category budgets, future expenses, and a unified ledger.",
    stack: ["SQL", "JavaScript", "Statistical analysis"],
    repo: "https://github.com/neverthesameagain/Splitzy-Pay",
    live: "https://splitzy-pay-backend.vercel.app",
    status: "shipped",
  },
  {
    id: "clearag",
    name: "CleaRAG",
    tagline: "A transparent retrieval-augmented question-answering system.",
    description:
      "Document-grounded QA over TXT/PDF ingestion with explicit answer grounding and explainable retrieval traces.",
    stack: ["Python", "RAG"],
    repo: "https://github.com/neverthesameagain/CleaRAG",
    status: "shipped",
  },
  {
    id: "spectrumharmony",
    name: "SpectrumHarmony",
    tagline: "AI-driven radio resource management for multi-floor Wi-Fi networks.",
    description:
      "Simulation and control framework to model, analyze, and optimize Wi-Fi networks in complex environments — built for RL-based radio resource management research.",
    stack: ["Python", "Reinforcement Learning"],
    repo: "https://github.com/neverthesameagain/SpectrumHarmony---RadioResource-Management-for-Arista-Netwrorks",
    status: "shipped",
  },
  {
    id: "modest",
    name: "Modest",
    tagline: "Adaptive content moderation under uncertainty.",
    description:
      "A content moderation system designed around uncertainty-aware decisions rather than binary classification.",
    stack: ["Python"],
    repo: "https://github.com/neverthesameagain/modest",
    status: "shipped",
  },
  {
    id: "isitevenhuman",
    name: "isitevenhuman?",
    tagline: "AI text detection engine.",
    description:
      "Paste any text and see whether it was written by a human or generated by AI — with per-sentence, color-coded breakdowns and full feature transparency, built on NLP, deep learning embeddings, and classical statistical analysis.",
    stack: ["Python", "NLP", "Deep Learning"],
    repo: "https://github.com/neverthesameagain/isitevenhuman-",
    status: "shipped",
  },
  {
    id: "recurlens",
    name: "RecurLens",
    tagline: "A recursive, multimodal reasoning system built on Gemini.",
    description:
      "Deliberately pauses before responding — listens to speech, analyzes images, evaluates ambiguity, and iteratively refines its own understanding before producing an answer.",
    stack: ["TypeScript", "Multimodal"],
    repo: "https://github.com/neverthesameagain/RecurLens",
    live: "https://recur-lense.vercel.app",
    status: "shipped",
  },
  {
    id: "lossless",
    name: "LossLess",
    tagline: "Amazon ML Challenge 2025 — top 0.9% of 27,600+ teams.",
    description:
      "End-to-end pipeline predicting product prices from multimodal (text + image) listings. A text-only DistilBERT architecture, trained on 75,000 listings, reached 45.72 SMAPE — competitive with full multimodal approaches.",
    stack: ["Python", "DistilBERT"],
    repo: "https://github.com/neverthesameagain/LossLess---Amazon-ML-Challenge-2025",
    status: "shipped",
  },
];

// Everything else in the GitHub account — smaller/experimental repos, listed as-is from
// GitHub's own metadata (name + language + real description where one exists). Ordered by
// last-updated, most recent first. Excludes: this portfolio repo, the GitHub profile-config
// repo, and repos already covered as full research publications above.
export type ArchiveRepo = {
  name: string;
  repo: string;
  language: string | null;
  description: string | null;
};

export const archiveRepos: ArchiveRepo[] = [
  { name: "Arithmetic-Coding", repo: "Arithmetic-Coding", language: "Python", description: null },
  { name: "EIE-Economic-Intelligence-Engine", repo: "EIE-Economic-Intelligence-Engine", language: "Jupyter Notebook", description: null },
  { name: "Multivariate-custom-Dataset-for-Human-AI-Text", repo: "Multivariate-custom-Dataset-for-Human-AI-Text", language: "Python", description: "Multivariate custom Dataset for Human/AI Text" },
  { name: "ConnectFour", repo: "ConnectFour", language: "Python", description: null },
  { name: "Autonomous-Ackermann-Explorer", repo: "Autonomous-Ackermann-Explorer", language: "Python", description: null },
  { name: "3D-Human-Motion-Capture-and-Animation", repo: "3D-Human-Motion-Capture-and-Animation", language: "MATLAB", description: null },
  { name: "Debris-Detection-Realtime", repo: "Debris-Detection-Realtime", language: "HTML", description: null },
  { name: "Personalised-MCP-server", repo: "Personalised-MCP-server", language: "Python", description: null },
  { name: "PizzaBuilder-SWE-2025", repo: "PizzaBuilder-SWE-2025", language: "Java", description: null },
  { name: "All-You-Need", repo: "All-You-Need", language: "HTML", description: null },
  { name: "AYCI-The-Project", repo: "AYCI-The-Project", language: "Python", description: null },
  { name: "PanEvaporiMeter", repo: "PanEvaporiMeter", language: "C++", description: null },
  { name: "iac", repo: "iac", language: "HTML", description: null },
  { name: "Automated-Data-Extraction-from-Gov-Websites", repo: "Automated-Data-Extraction-from-Gov-Websites", language: null, description: null },
  { name: "What-ya-Wearing", repo: "What-ya-Wearing", language: "Jupyter Notebook", description: null },
  { name: "DSA-that-is-actually-interesting", repo: "DSA-that-is-actually-interesting", language: null, description: null },
  { name: "Behaviour-Simulation-Challenge-by-Adobe", repo: "Behaviour-Simulation-Challenge-by-Adobe", language: "Jupyter Notebook", description: null },
  { name: "Parameter-Extraction-of-Diodes-and-MOSFETS", repo: "Parameter-Extraction-of-Diodes-and-MOSFETS", language: "Jupyter Notebook", description: null },
  { name: "KLM52Z-Microprocessor-Projects", repo: "KLM52Z-Microprocessor-Projects", language: "C", description: null },
  { name: "Analysis-in-MATLAB-", repo: "Analysis-in-MATLAB-", language: "MATLAB", description: null },
  { name: "AYCI", repo: "AYCI", language: "Python", description: "This is our project repository." },
];

export const githubProfile = "https://github.com/neverthesameagain";
